# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
julia:
  - release
  - nightly
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.add("ColorTypes"); Pkg.add("Colors"); Pkg.add("ColorVectorSpace")'
  - julia -e 'Pkg.add("Tk")'
  - julia -e 'Pkg.add("Images"); Pkg.checkout("Images", "teh/colors")'
  - julia -e 'Pkg.add("Gadfly"); Pkg.checkout("Gadfly", "teh/colors2")'
  - julia -e 'Pkg.checkout("DataArrays")'
  - julia -e 'Pkg.checkout("Hexagons")'
  - julia -e 'Pkg.checkout("Compose", "teh/colors2")'
  - julia -e 'Pkg.add("Cairo"); Pkg.checkout("Cairo", "teh/colors2")'
  - julia -e 'Pkg.add("Graphics"); Pkg.checkout("Graphics", "teh/colors")'
  - julia -e 'Pkg.add("Winston"); Pkg.checkout("Winston", "teh/colors")'
  - julia -e 'Pkg.add("ProfileView"); Pkg.checkout("ProfileView", "teh/colors")'
  - julia -e 'Pkg.test("Images")'
  - julia -e 'Pkg.test("Cairo")'
  - julia -e 'Pkg.test("Graphics")'
  - julia -e 'Pkg.test("Gadfly")'
  - xvfb-run julia -e 'Pkg.test("Winston"); Pkg.test("ProfileView")'
